#ifndef STATUS_H
#define STATUS_H

typedef enum{
    STATUS_OK = 0,
    STATUS_ERROR = 1,
    STATUS_NULL_POINTER = 2,
    STATUS_INVALID_ARGUMENT = 3,
    STATUS_PERMISSION_DENIED = 4,
    STATUS_ALREADY_EXISTS = 5,
    STATUS_FULL = 6,
    STATUS_BUSY = 7, 
    STATUS_NOT_INITIALIZED = 8 
    
    
}status_e;

#endif // STATUS_H